// ─── DATA DUMMY TUGAS BELAJAR ────────────────────────────────────────────────
export type TugasBelajar = {
  nama: string;
  no: number;
  nipLama: string;
  nipBaru: string;
  usia: number;
  golongan: string;
  pendidikanSaatDaftar: string;
  jenjangPendidikan: "S2" | "S3" | "S1" | "D4";
  jenisTugasBelajar: "Tugas Belajar" | "Izin Belajar";
  gelarAkademik: string;
  lokasi: "DN" | "LN" | "Linkage";
  programJurusan: string;
  namaUniversitas: string;
  lokasiUniversitas: string;
  programJurusanLinkage?: string;
  namaUniversitasLinkage?: string;
  lokasiUniversitasLinkage?: string;
  statusStudi: "Aktif" | "Lulus" | "Cuti" | "Dropout";
  pembiayaan: "Full" | "Sharing Cost";
  sumberPendanaan: string;
  suratTugasBelajar: string;
  tanggalSTTB: string;
  jangkaWaktuAwal: string;
  jangkaWaktuAkhir: string;
  nomorIjasah?: string;
  tanggalIjasah?: string;
  suratPengembalian?: string;
  tanggalSuratPengembalian?: string;
  keterangan?: string;
  statusKelulusan: "Lulus" | "Belum Lulus" | "Proses" | "-";
  judulTugasAkhir?: string;
  alamatEmail: string;
  nomorHP: string;
  keywordTA?: string;
  tahunLulus?: number;
  tahunMulai: number;
  unitEselon2: string;
};

export const dummyTugasBelajar: TugasBelajar[] = [
  {
    no: 1,
    nama: "Budi Santoso",
    nipLama: "197503152000031001",
    nipBaru: "197503152000031001",
    usia: 38,
    golongan: "III/c",
    pendidikanSaatDaftar: "S1",
    jenjangPendidikan: "S2",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "M.Si",
    lokasi: "DN",
    programJurusan: "Manajemen Sumber Daya Manusia",
    namaUniversitas: "Universitas Indonesia",
    lokasiUniversitas: "Depok, Jawa Barat",
    statusStudi: "Lulus",
    pembiayaan: "Full",
    sumberPendanaan: "APBN",
    suratTugasBelajar: "B-1234/HRD/2022",
    tanggalSTTB: "2022-02-15",
    jangkaWaktuAwal: "2022-03-01",
    jangkaWaktuAkhir: "2024-02-28",
    nomorIjasah: "UI-2024-12345",
    tanggalIjasah: "2024-03-15",
    statusKelulusan: "Lulus",
    judulTugasAkhir: "Analisis Pengaruh Pelatihan terhadap Kinerja ASN",
    alamatEmail: "budi.santoso@bpsdm.go.id",
    nomorHP: "081234567890",
    keywordTA: "pelatihan, kinerja, ASN, manajemen",
    tahunLulus: 2024,
    tahunMulai: 2022,
    unitEselon2: "Biro Kepegawaian",
  },
  {
    no: 2,
    nama: "Siti Rahayu",
    nipLama: "198106202003122003",
    nipBaru: "198106202003122003",
    usia: 32,
    golongan: "III/b",
    pendidikanSaatDaftar: "S1",
    jenjangPendidikan: "S2",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "M.Pd",
    lokasi: "DN",
    programJurusan: "Teknologi Pendidikan",
    namaUniversitas: "Universitas Negeri Yogyakarta",
    lokasiUniversitas: "Yogyakarta",
    statusStudi: "Aktif",
    pembiayaan: "Full",
    sumberPendanaan: "APBN",
    suratTugasBelajar: "B-2341/HRD/2023",
    tanggalSTTB: "2023-07-10",
    jangkaWaktuAwal: "2023-08-01",
    jangkaWaktuAkhir: "2025-07-31",
    statusKelulusan: "Belum Lulus",
    alamatEmail: "siti.rahayu@bpsdm.go.id",
    nomorHP: "082345678901",
    tahunMulai: 2023,
    unitEselon2: "Pusat Pengembangan Kompetensi",
  },
  {
    no: 3,
    nama: "Ahmad Fauzi",
    nipLama: "197812102005011002",
    nipBaru: "197812102005011002",
    usia: 42,
    golongan: "IV/a",
    pendidikanSaatDaftar: "S2",
    jenjangPendidikan: "S3",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "Ph.D",
    lokasi: "LN",
    programJurusan: "Public Administration",
    namaUniversitas: "University of Melbourne",
    lokasiUniversitas: "Melbourne, Australia",
    statusStudi: "Aktif",
    pembiayaan: "Full",
    sumberPendanaan: "LPDP",
    suratTugasBelajar: "B-0987/HRD/2022",
    tanggalSTTB: "2022-10-01",
    jangkaWaktuAwal: "2023-02-01",
    jangkaWaktuAkhir: "2026-01-31",
    statusKelulusan: "Proses",
    judulTugasAkhir: "Governance Reform in Indonesian Civil Service",
    alamatEmail: "ahmad.fauzi@bpsdm.go.id",
    nomorHP: "083456789012",
    keywordTA: "governance, reform, civil service, Indonesia",
    tahunMulai: 2023,
    unitEselon2: "Sekretariat Badan",
  },
  {
    no: 4,
    nama: "Dewi Kusuma",
    nipLama: "198503052006042001",
    nipBaru: "198503052006042001",
    usia: 35,
    golongan: "III/c",
    pendidikanSaatDaftar: "S1",
    jenjangPendidikan: "S2",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "M.Kes",
    lokasi: "Linkage",
    programJurusan: "Kesehatan Masyarakat",
    namaUniversitas: "Universitas Gadjah Mada",
    lokasiUniversitas: "Yogyakarta",
    programJurusanLinkage: "Public Health Management",
    namaUniversitasLinkage: "University of Queensland",
    lokasiUniversitasLinkage: "Brisbane, Australia",
    statusStudi: "Lulus",
    pembiayaan: "Sharing Cost",
    sumberPendanaan: "APBN + LPDP",
    suratTugasBelajar: "B-3456/HRD/2021",
    tanggalSTTB: "2021-05-20",
    jangkaWaktuAwal: "2021-08-01",
    jangkaWaktuAkhir: "2023-07-31",
    nomorIjasah: "UGM-2023-67890",
    tanggalIjasah: "2023-09-01",
    statusKelulusan: "Lulus",
    judulTugasAkhir: "Program Kesehatan Masyarakat Berbasis Komunitas",
    alamatEmail: "dewi.kusuma@bpsdm.go.id",
    nomorHP: "084567890123",
    keywordTA: "kesehatan masyarakat, komunitas, program",
    tahunLulus: 2023,
    tahunMulai: 2021,
    unitEselon2: "Pusat Pengembangan Kompetensi Teknis",
  },
  {
    no: 5,
    nama: "Rahmat Hidayat",
    nipLama: "199001152012031004",
    nipBaru: "199001152012031004",
    usia: 29,
    golongan: "III/a",
    pendidikanSaatDaftar: "S1",
    jenjangPendidikan: "S2",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "M.T",
    lokasi: "DN",
    programJurusan: "Informatika",
    namaUniversitas: "Institut Teknologi Bandung",
    lokasiUniversitas: "Bandung, Jawa Barat",
    statusStudi: "Aktif",
    pembiayaan: "Full",
    sumberPendanaan: "APBN",
    suratTugasBelajar: "B-5678/HRD/2024",
    tanggalSTTB: "2024-01-15",
    jangkaWaktuAwal: "2024-02-01",
    jangkaWaktuAkhir: "2026-01-31",
    statusKelulusan: "Belum Lulus",
    alamatEmail: "rahmat.hidayat@bpsdm.go.id",
    nomorHP: "085678901234",
    tahunMulai: 2024,
    unitEselon2: "Pusat Inovasi & Teknologi",
  },
  {
    no: 6,
    nama: "Nurul Aini",
    nipLama: "198709282009012005",
    nipBaru: "198709282009012005",
    usia: 37,
    golongan: "III/d",
    pendidikanSaatDaftar: "S1",
    jenjangPendidikan: "S2",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "M.A",
    lokasi: "LN",
    programJurusan: "International Relations",
    namaUniversitas: "Leiden University",
    lokasiUniversitas: "Leiden, Belanda",
    statusStudi: "Lulus",
    pembiayaan: "Full",
    sumberPendanaan: "LPDP",
    suratTugasBelajar: "B-7890/HRD/2021",
    tanggalSTTB: "2021-09-01",
    jangkaWaktuAwal: "2021-10-01",
    jangkaWaktuAkhir: "2023-09-30",
    nomorIjasah: "LU-2023-11111",
    tanggalIjasah: "2023-11-15",
    statusKelulusan: "Lulus",
    judulTugasAkhir: "Indonesia-EU Diplomatic Relations in Post-Pandemic Era",
    alamatEmail: "nurul.aini@bpsdm.go.id",
    nomorHP: "086789012345",
    keywordTA: "diplomasi, Indonesia, EU, pandemi",
    tahunLulus: 2023,
    tahunMulai: 2021,
    unitEselon2: "Biro Hukum & Kerja Sama",
  },
  {
    no: 7,
    nama: "Hendra Wijaya",
    nipLama: "198204112004011003",
    nipBaru: "198204112004011003",
    usia: 44,
    golongan: "IV/b",
    pendidikanSaatDaftar: "S2",
    jenjangPendidikan: "S3",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "Dr.",
    lokasi: "DN",
    programJurusan: "Administrasi Publik",
    namaUniversitas: "Universitas Brawijaya",
    lokasiUniversitas: "Malang, Jawa Timur",
    statusStudi: "Lulus",
    pembiayaan: "Full",
    sumberPendanaan: "APBN",
    suratTugasBelajar: "B-1122/HRD/2020",
    tanggalSTTB: "2020-03-10",
    jangkaWaktuAwal: "2020-09-01",
    jangkaWaktuAkhir: "2023-08-31",
    nomorIjasah: "UB-2023-22222",
    tanggalIjasah: "2023-10-01",
    statusKelulusan: "Lulus",
    judulTugasAkhir: "Model Reformasi Birokrasi Berbasis Kinerja",
    alamatEmail: "hendra.wijaya@bpsdm.go.id",
    nomorHP: "087890123456",
    keywordTA: "birokrasi, reformasi, kinerja, model",
    tahunLulus: 2023,
    tahunMulai: 2020,
    unitEselon2: "Sekretariat Badan",
  },
  {
    no: 8,
    nama: "Yuni Astuti",
    nipLama: "199205302015042002",
    nipBaru: "199205302015042002",
    usia: 28,
    golongan: "III/a",
    pendidikanSaatDaftar: "S1",
    jenjangPendidikan: "S2",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "M.Ak",
    lokasi: "DN",
    programJurusan: "Akuntansi",
    namaUniversitas: "Universitas Padjadjaran",
    lokasiUniversitas: "Bandung, Jawa Barat",
    statusStudi: "Aktif",
    pembiayaan: "Sharing Cost",
    sumberPendanaan: "APBN + Mandiri",
    suratTugasBelajar: "B-3344/HRD/2024",
    tanggalSTTB: "2024-03-01",
    jangkaWaktuAwal: "2024-04-01",
    jangkaWaktuAkhir: "2026-03-31",
    statusKelulusan: "Belum Lulus",
    alamatEmail: "yuni.astuti@bpsdm.go.id",
    nomorHP: "088901234567",
    tahunMulai: 2024,
    unitEselon2: "Biro Keuangan",
  },
  {
    no: 9,
    nama: "Dimas Prasetyo",
    nipLama: "198801192010011006",
    nipBaru: "198801192010011006",
    usia: 38,
    golongan: "III/c",
    pendidikanSaatDaftar: "S1",
    jenjangPendidikan: "S2",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "M.Hum",
    lokasi: "LN",
    programJurusan: "Hukum Internasional",
    namaUniversitas: "University of Amsterdam",
    lokasiUniversitas: "Amsterdam, Belanda",
    statusStudi: "Cuti",
    pembiayaan: "Full",
    sumberPendanaan: "LPDP",
    suratTugasBelajar: "B-5566/HRD/2022",
    tanggalSTTB: "2022-06-15",
    jangkaWaktuAwal: "2022-09-01",
    jangkaWaktuAkhir: "2024-08-31",
    keterangan: "Cuti sakit, perpanjangan diajukan",
    statusKelulusan: "Proses",
    alamatEmail: "dimas.prasetyo@bpsdm.go.id",
    nomorHP: "089012345678",
    tahunMulai: 2022,
    unitEselon2: "Biro Hukum & Kerja Sama",
  },
  {
    no: 10,
    nama: "Rina Melati",
    nipLama: "198612252008012007",
    nipBaru: "198612252008012007",
    usia: 40,
    golongan: "III/d",
    pendidikanSaatDaftar: "S1",
    jenjangPendidikan: "S2",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "M.Pd",
    lokasi: "DN",
    programJurusan: "Manajemen Pendidikan",
    namaUniversitas: "Universitas Negeri Malang",
    lokasiUniversitas: "Malang, Jawa Timur",
    statusStudi: "Lulus",
    pembiayaan: "Full",
    sumberPendanaan: "APBN",
    suratTugasBelajar: "B-7788/HRD/2021",
    tanggalSTTB: "2021-01-20",
    jangkaWaktuAwal: "2021-02-01",
    jangkaWaktuAkhir: "2023-01-31",
    nomorIjasah: "UNM-2023-33333",
    tanggalIjasah: "2023-03-10",
    statusKelulusan: "Lulus",
    judulTugasAkhir: "Implementasi Manajemen Berbasis Sekolah",
    alamatEmail: "rina.melati@bpsdm.go.id",
    nomorHP: "081111234567",
    keywordTA: "manajemen sekolah, MBS, implementasi",
    tahunLulus: 2023,
    tahunMulai: 2021,
    unitEselon2: "Pusat Pengembangan Kompetensi",
  },
  {
    no: 11,
    nama: "Fajar Nugroho",
    nipLama: "199304142016011008",
    nipBaru: "199304142016011008",
    usia: 27,
    golongan: "III/a",
    pendidikanSaatDaftar: "S1",
    jenjangPendidikan: "S2",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "M.Kom",
    lokasi: "DN",
    programJurusan: "Ilmu Komputer",
    namaUniversitas: "Institut Pertanian Bogor",
    lokasiUniversitas: "Bogor, Jawa Barat",
    statusStudi: "Aktif",
    pembiayaan: "Full",
    sumberPendanaan: "APBN",
    suratTugasBelajar: "B-9900/HRD/2024",
    tanggalSTTB: "2024-07-01",
    jangkaWaktuAwal: "2024-08-01",
    jangkaWaktuAkhir: "2026-07-31",
    statusKelulusan: "Belum Lulus",
    alamatEmail: "fajar.nugroho@bpsdm.go.id",
    nomorHP: "082222345678",
    tahunMulai: 2024,
    unitEselon2: "Pusat Inovasi & Teknologi",
  },
  {
    no: 12,
    nama: "Mega Wulandari",
    nipLama: "198410082006042004",
    nipBaru: "198410082006042004",
    usia: 42,
    golongan: "IV/a",
    pendidikanSaatDaftar: "S2",
    jenjangPendidikan: "S3",
    jenisTugasBelajar: "Tugas Belajar",
    gelarAkademik: "Ph.D",
    lokasi: "LN",
    programJurusan: "Economics",
    namaUniversitas: "National University of Singapore",
    lokasiUniversitas: "Singapura",
    statusStudi: "Aktif",
    pembiayaan: "Full",
    sumberPendanaan: "LPDP",
    suratTugasBelajar: "B-1234/HRD/2023",
    tanggalSTTB: "2023-11-01",
    jangkaWaktuAwal: "2024-01-01",
    jangkaWaktuAkhir: "2027-12-31",
    statusKelulusan: "Proses",
    alamatEmail: "mega.wulandari@bpsdm.go.id",
    nomorHP: "083333456789",
    tahunMulai: 2024,
    unitEselon2: "Biro Perencanaan",
  },
];
